apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-deploy-adservice-
spec:
  entrypoint: build-deploy-adservice
  arguments:
    parameters:
      - name: adservice-image
        value: gcr.io/rising-area-331809/adservice:3.3.4
  volumes:
    - name: gcr-credentials
      secret:
        secretName: gcr-registry-access
        items:
          - key: .dockerconfigjson
            path: config.json

  templates:
    - name: build-deploy-adservice
      steps:
        - - name: checkout-build
            template: build-adservice
            arguments:
              parameters:
                - name: git-repo
                  value: https://github.com/Coit-IO/coit-home-commerce.git
                - name: git-revision
                  value: develop
        - - name: kubectl-deploy
            template: kubectl-apply
        - - name: change-image
            template: kubectl-set-image
    - name: build-adservice
      inputs:
        parameters:
          - name: git-repo
          - name: git-revision
        artifacts:
          - name: source-code
            path: /source/code
            git:
              repo: "{{inputs.parameters.git-repo}}"
              revision: "{{inputs.parameters.git-revision}}"
      container:
        image: gcr.io/kaniko-project/executor:latest
        args: 
          - "--context=/source/code/src/adservice"
          - "--dockerfile=/source/code/src/adservice/Dockerfile"
          - "--destination={{workflow.parameters.adservice-image}}"
        volumeMounts:
          - name: gcr-credentials
            mountPath: "/kaniko/.docker/"
    - name: kubectl-apply
      inputs:
        artifacts:
          - name: manifests-source
            path: /manifests
            git:
              repo: https://github.com/Coit-IO/coit-home-commerce.git
              revision: "develop"
      container:
        image: bitnami/kubectl:1.20.13
        args: 
          - "apply"
          - "-f"
          - "/manifests/kubernetes-manifests/adservice.yaml"
    - name: kubectl-set-image
      container:
        image: bitnami/kubectl:1.20.13
        args:
          - "set"
          - "image"
          - "deployment/adservice"
          - "server={{workflow.parameters.adservice-image}}"
